version: "3.8"

networks:
  corp:
    driver: bridge

services:
  nest-app-second:
    container_name: nest-app-second
    build:
      context: ./
      cache_from:
        - my-base-image:nx-base
      dockerfile: ./apps/nest-app-second/Dockerfile
      args:
        NODE_ENV: "development"
    image: nest-app-second:nx-dev
    ports:
      - 3333:3333
    environment:
      NODE_ENV: "development"
      PORT: 3333
    networks:
      - corp
    restart: on-failure
  nest-nx:
    container_name: nest-nx
    build:
      context: ./
      cache_from:
        - my-base-image:nx-base
      dockerfile: ./apps/nest-nx/Dockerfile
      args:
        NODE_ENV: "development"
    image: nest-nx:nx-dev
    ports:
      - 4444:4444
    environment:
      NODE_ENV: "development"
      PORT: 4444
    networks:
      - corp
    restart: on-failure
